name: Daily Paper Fetch

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  fetch-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests feedparser PyGithub

    - name: Run fetch script
      env:
        TARGET_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}      # GitHub 的自动 token
        TARGET_REPO_NAME: "YurenHao0426/awesome-llm-bias-papers"
        UIUC_API_KEY: ${{ secrets.UIUC_API_KEY }}          # 取出你的API密钥
      run: python fetch_papers.py
