name: Daily Paper Fetch

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  fetch-and-update-readme:
    runs-on: ubuntu-latest  # 或 ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests sentence-transformers feedparser PyGithub

    - name: Run script
      env:
        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        TARGET_REPO_NAME: "YurenHao0426/llm-bias-papers"
      run: python scripts/fetch_papers.py
